name: maktabati
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

  cupertino_icons: ^1.0.8

  http: ^0.13.6
  flutter_secure_storage: ^9.2.4

  provider: ^6.0.5

  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

